version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:latest
    working_directory: ~/circleci-workflows
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-dependencies
      - run: yarn install
      - save_cache:
          key: v1-dependencies
          paths:
            - node_modules
      - run: echo "push to npm"
      - run: npm adduser 